"""Kernel 2014.6 batch B3: the league artifacts (data only; nothing in runtime/ reads them yet).

Structural and hygiene checks on the committed artifacts run always; they need no source
data. The builders' --check runs (full rebuilds from the gated sources, minutes long) run only
when the fetched sources are present ($SOURCES_2010_2014_DIR) and B3_BUILDER_CHECKS=1, because
raw data stays out of the repository.
"""
import json
import os
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts/research"))
sys.path.insert(0, str(ROOT))

import build_2010_2014_league_base as base  # noqa: E402
import pre_build_specification  # noqa: E402

DATA = ROOT / "library/data"
ARTIFACTS = {
    "field_position": DATA / "2010_2014w4_nfl_field_position_model.json",
    "drive_model": DATA / "2010_2014w4_nfl_drive_model.json",
    "aggregate": DATA / "2010_2014w4_nfl_aggregate_baseline.json",
    "scoring": DATA / "2010_2014w4_scoring_decisions.json",
    "usage": DATA / "2010_2014w4_nfl_position_usage_baseline.json",
    "injury": DATA / "2010_2014w4_nfl_injury_calibration.json",
    "participation": DATA / "2013_2014_participation_structure.json",
    "conditions": DATA / "2014_conditions_calibration.json",
    "venues": DATA / "2014_venues.json",
    "climatology": DATA / "2010_2013_venue_climatology.json",
}
RECORDS = ("library/2010_2014_calibration_base.md", "library/2010_2014_scoring_decisions_calibration.md",
           "library/2014_context_and_conditions_calibration.md")
RULES = pre_build_specification.frozen_rules()
_CACHE = {}


def load(name):
    if name not in _CACHE:
        _CACHE[name] = json.loads(ARTIFACTS[name].read_text())
    return _CACHE[name]


def keys(obj, out=None):
    out = set() if out is None else out
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.add(k)
            keys(v, out)
    elif isinstance(obj, list):
        for v in obj:
            keys(v, out)
    return out


class HygieneTests(unittest.TestCase):
    def test_every_artifact_records_the_specification(self):
        digest = pre_build_specification.FROZEN_SHA256
        for name in ARTIFACTS:
            self.assertEqual(load(name).get("specification_sha256"), digest, name)

    def test_no_club_game_player_or_date_field_in_the_fits(self):
        for name in ("field_position", "drive_model", "aggregate", "scoring", "usage", "injury", "participation",
                     "conditions"):
            art = load(name)
            found = sorted(k for k in keys({k: v for k, v in art.items()
                                           if k not in ("sources", "EXPLAINED", "provenance", "league_base",
                                                        "carried_from")})
                           if base.forbidden(k))
            self.assertEqual(found, [], name)

    def test_no_row_after_the_2014_cut_and_no_later_season(self):
        cut = RULES["data_window"]["cut_2014"]["max_game_date"]
        for name in ARTIFACTS:
            text = ARTIFACTS[name].read_text()
            for season in range(2015, 2030):
                self.assertNotIn('"%d"' % season, text, name)
            for later in ("2014-09-30", "2014-10-0", "2014-11", "2014-12"):
                self.assertNotIn(later, text, name)
        self.assertEqual(cut, "2014-09-29")

    def test_information_boundary_is_stated(self):
        for name in ("field_position", "drive_model", "aggregate", "scoring", "usage", "injury", "participation",
                     "conditions"):
            self.assertIn("no club, game, player or date field", load(name)["information_boundary"], name)

    def test_records_carry_generated_tables(self):
        for path in RECORDS:
            text = (ROOT / path).read_text()
            body = text.split("<!-- generated:begin -->", 1)[1].split("<!-- generated:end -->", 1)[0]
            self.assertIn("Generated by `scripts/research/", body, path)
            self.assertGreater(len(body), 500, path)


class LeagueBaseTests(unittest.TestCase):
    def test_validate_passes(self):
        self.assertEqual(base.validate(load("field_position"), load("drive_model"), load("aggregate")), [])

    def test_partition_and_filters(self):
        fp = load("field_position")
        part = fp["partition"]
        self.assertEqual(part["ot_excluded"], RULES["structural_filters"]["excluded_2010_2011_overtime_drives"])
        self.assertEqual(sum(part["counts"].values()) + part["ot_excluded"], part["drives"])
        season = fp["kick_fields"].index("season")
        self.assertTrue(fp["kickoff_pool"])
        self.assertFalse([r for r in fp["kickoff_pool"] if r[season] < 2011])
        t_season = fp["tuple_fields"].index("season")
        for name in ("ot_first", "ot_sudden"):
            for pool in fp["pools"][name].values():
                self.assertFalse([t for t in pool if t[t_season] < 2012])
        for cells in list(fp["late_counts"].values()) + list(fp["h1_late_counts"].values()):
            self.assertGreaterEqual(sum(cells.values()), RULES["thresholds"]["MIN_CELL"])
        for name in ("ot_first", "ot_sudden"):
            self.assertGreaterEqual(sum(fp[name + "_counts"].values()), RULES["thresholds"]["MIN_CELL"])

    def test_fields_extend_the_committed_lists(self):
        fp = load("field_position")
        v2 = json.loads((DATA / "2012_nfl_field_position_model.json").read_text())
        for name in ("tuple_fields", "kick_fields", "punt_fields", "turnover_fields"):
            self.assertEqual(fp[name][:len(v2[name])], v2[name], name)

    def test_constants_reproduce_the_specification(self):
        c = load("field_position")["constants"]
        eoh = RULES["end_of_half"]
        self.assertEqual(c["spike_window"]["pre_divergence_max_seconds"], eoh["SPIKE_WINDOW"])
        self.assertEqual(c["early_field_goal"]["max_seconds"], eoh["EARLY_FG_SECONDS"])
        self.assertEqual(c["w5a_second_pass"]["result"], "pass")

    def test_clock_scale_and_rates(self):
        fp, dm = load("field_position"), load("drive_model")
        self.assertEqual(fp["clock_scale"], dm["clock_scale"])
        rates = dm["rates"]
        self.assertEqual([sum(v[i] for v in rates["fg_by_distance"].values()) for i in (0, 1)], rates["field_goal"])
        for name in ("field_goal", "extra_point", "two_point", "td_type_pass", "turnover_type_interception"):
            k, n = rates[name]
            self.assertTrue(0 <= k <= n and n > 0, name)
        fgd = dm["field_goal_distance"]
        self.assertLess(abs(fgd["slope_per_yard"] - fgd["second_pass"]["slope_per_yard"]), 2 * fgd["slope_se"])
        self.assertEqual(set(fgd["bands"]), set(rates["fg_by_distance"]))

    def test_second_passes_and_reconciliation_pass(self):
        fp, dm, agg = load("field_position"), load("drive_model"), load("aggregate")
        for block in (fp["second_pass"], dm["second_pass"], fp["annotation_second_pass"], agg["reconciliation"]):
            self.assertEqual(block["result"], "pass")
            self.assertFalse([r for r in block["comparison"] if r.get("status") == "UNEXPLAINED"])
        self.assertEqual(fp["reconciliation"]["result"], "pass")

    def test_annotations(self):
        fp = load("field_position")
        fields = fp["tuple_fields"]
        pen, fum, place, start = (fields.index(k) for k in ("pen", "fumbles", "placement", "start"))
        n = 0
        for row in fp["pools"]["neutral"]:
            for pool in row:
                for t in pool:
                    n += 1
                    self.assertTrue(t[place][0] <= t[start] <= t[place][1])
                    for p in t[pen]:
                        self.assertEqual(len(p), len(fp["pen_fields"]))
                        self.assertIn(p[4], ("A", "D", "X"))
                        self.assertIn(p[5], ("N", "S", "K"))
                    for f in t[fum]:
                        self.assertEqual(len(f), len(fp["fumble_fields"]))
        self.assertGreater(n, 10000)
        kick = fp["kick_fields"]
        e, adjust, pen_k, poss = (kick.index(k) for k in ("enforcement", "spot_adjust", "pen", "possession"))
        retained = 0
        for r in fp["kickoff_pool"]:
            # enforcement stays the total: spot_adjust plus the penalty effect (minus the helping
            # yards in the receiving frame, plus them in the kicking frame of a retained kick).
            total = sum(p[2] for p in r[pen_k] if p[3] == "A" and p[2] is not None)
            effect = total if r[poss] == "kicking" else -total
            self.assertEqual(r[e], r[adjust] + effect)
            retained += r[poss] == "kicking"
        self.assertEqual(retained, len(fp["retained_kick_pools"]["kickoff"]))
        self.assertEqual(set(fp["retained_kick_pools"]), {"kickoff", "free_kick", "punt"})
        self.assertEqual(len(fp["emphasis_counts"]), 5)


class CompanionArtifactTests(unittest.TestCase):
    def test_scoring(self):
        sc, dm = load("scoring"), load("drive_model")
        self.assertEqual(sum(sc["team_games"].values()), 2170)
        self.assertEqual(sc["extra_point_reference"]["value"], dm["rates"]["extra_point"])
        chart = sc["try"]["decision_chart"]
        for cell in chart:
            time = cell.split("|")[0]
            # Amendment A1: Q1-Q3 never merges with the fourth quarter.
            self.assertTrue(time == "Q1-Q3" or "Q1-Q3" not in time, cell)
        self.assertEqual(sum(v["tries"] for v in chart.values()),
                         sum(n for _, n in sc["try"]["tries_by_season"].values()))
        for row in sc["denominators"]["comparison"]:
            self.assertNotEqual(row.get("status"), "differs", row)
        self.assertIsNotNone(sc["try_snap_participation"]["offense"]["per_two_point_try"])

    def test_usage(self):
        from runtime import usage
        self.assertEqual(usage.validate(load("usage")), [])
        self.assertEqual(load("usage")["second_pass"]["result"], "pass")

    def test_injury(self):
        import build_2010_2014_injury_calibration as injury
        from runtime.participation import SCRIMMAGE_SLOT_MIX
        art = load("injury")
        self.assertEqual(injury.validate(art), [])
        self.assertEqual(art["recommended"]["position_relative_risk_per_snap"]["slot_mix"], dict(SCRIMMAGE_SLOT_MIX))
        self.assertIn("acceptance_bands_for_kernel_2014_6", art)
        self.assertEqual(art["data_by_season"]["2014w4"]["severity_report_onsets_footprint"],
                         "not used (games after the cut)")

    def test_participation_is_informational(self):
        self.assertIn("informational", load("participation")["status"])

    def test_conditions(self):
        art = load("conditions")
        for name, outcome in art["outcomes"].items():
            self.assertTrue(set(outcome["adopted"]) <= set(outcome["kept_by_rule"]), name)
            for term in ("alt", "alt_edge"):
                if term in outcome["live_slopes"]:
                    self.assertEqual(outcome["live_slopes"][term], 0.0, name)
            if outcome["channel"] == "report only" or outcome["channel"].startswith("report only"):
                self.assertEqual(outcome["live_slopes"], {}, name)
        self.assertFalse([k for k in keys(art) if k in ("kicker", "punter", "off_cs", "def_cs")])
        venues, climate = load("venues"), load("climatology")
        for club, venue in venues["club_home_venue_2014"].items():
            self.assertIn(venue, venues["venues"], club)
            self.assertEqual(set(climate["venues"][venue]), set(climate["month_bins"]), venue)


@unittest.skipUnless(os.environ.get("SOURCES_2010_2014_DIR") and os.environ.get("B3_BUILDER_CHECKS") == "1",
                     "builder --check runs need the fetched sources and B3_BUILDER_CHECKS=1")
class BuilderCheckTests(unittest.TestCase):
    def run_check(self, script, *args):
        result = subprocess.run([sys.executable, str(ROOT / "scripts/research" / script), "--check", *args],
                                capture_output=True, text=True, cwd=ROOT)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_league_base(self):
        self.run_check("build_2010_2014_league_base.py")
        self.run_check("build_2010_2014_league_base.py", "--stage", "core")

    def test_scoring(self):
        self.run_check("build_2010_2014_scoring_decisions.py")

    def test_usage_injury_participation(self):
        self.run_check("build_2010_2014_usage_baseline.py")
        self.run_check("build_2010_2014_injury_calibration.py")
        self.run_check("build_2013_2014_participation_structure.py")

    def test_conditions(self):
        self.run_check("build_2014_conditions_calibration.py")


if __name__ == "__main__":
    unittest.main()
