#!/usr/bin/env python3
"""League awards: formula shortlist, then an audited panel draw.

  python scripts/league_awards.py week N            # dry run: shortlists
  python scripts/league_awards.py week N --close    # draw and record
  python scripts/league_awards.py month NAME [--close]
  python scripts/league_awards.py render            # rewrite the award pages

The method is fixed in career/2013/awards/methodology.json before any
winner is drawn: one scoring formula per category, applied identically to
every player from the closed receipts; the top three in each conference form
the shortlist; the private service supplies the entropy for a weighted panel
pick among them, exactly as it does for a game. No real-world award result is
read anywhere.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import random
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from runtime.game_runner import _entropy_from_ref
from runtime.league import conference_of
from runtime.packets import canonical
from scripts.render_season_stats import load_receipts

AWARDS = ROOT / "career/2013/awards"
METHOD = AWARDS / "methodology.json"
RESULTS = AWARDS / "results.json"


def method():
    return json.loads(METHOD.read_text(encoding="utf-8"))


def score(category, player, m):
    f = m["formulas"][category]
    position = player.get("position")
    total = 0.0
    for part in f["parts"]:
        if part.get("positions") and position not in part["positions"]:
            continue
        for stat, weight in part["weights"].items():
            if stat == "fg_missed":
                value = player.get("field_goals_attempted", 0) - player.get("field_goals_made", 0)
            elif stat == "xp_missed":
                value = player.get("extra_points_attempted", 0) - player.get("extra_points_made", 0)
            elif stat == "punt_yards_over_45":
                value = player.get("punt_yards", 0) - 45 * player.get("punts", 0)
            else:
                value = player.get(stat, 0)
            total += weight * value
    return round(total, 2)


def eligible(category, player, m):
    f = m["formulas"][category]
    return not f.get("positions") or player.get("position") in f["positions"]


def period_weeks(kind, key, m):
    return [int(key)] if kind == "week" else m["months"][key]["weeks"]


def shortlists(kind, key, m):
    weeks = set(period_weeks(kind, key, m))
    totals = {}
    for receipt in load_receipts(ROOT / "career/2013/stats/game_receipts"):
        if int(receipt["week"]) not in weeks:
            continue
        for team, stats in receipt["team_stats"].items():
            for name, player in stats["players"].items():
                for category in m["categories"]:
                    if not eligible(category, player, m):
                        continue
                    row = totals.setdefault((conference_of(team), category, name, team),
                                            {"score": 0.0, "games": 0})
                    row["score"] = round(row["score"] + score(category, player, m), 2)
                    row["games"] += 1
    lists = {}
    for conference in ("AFC", "NFC"):
        for category in m["categories"]:
            rows = [(v["score"], name, team) for (c, cat, name, team), v in totals.items()
                    if c == conference and cat == category]
            rows.sort(key=lambda r: (-r[0], r[1], r[2]))
            lists["%s-%s" % (conference, category)] = [
                {"player": n, "team": t, "score": s} for s, n, t in rows[:m["shortlist_size"]]]
    return lists


def event_id(kind, key, award, m):
    tag = "week%02d" % int(key) if kind == "week" else key.lower()
    return "2013-award-%s-%s-%s" % (tag, award.lower(), m["procedure_tag"])


def packet(kind, key, award, shortlist, m, snapshot):
    return {"procedure": m["procedure"], "event_id": event_id(kind, key, award, m),
            "snapshot": snapshot, "period": {"kind": kind, "key": str(key)}, "award": award,
            "shortlist": shortlist, "panel_weights": m["panel_weights"][:len(shortlist)],
            "method_sha256": hashlib.sha256(METHOD.read_bytes()).hexdigest()}


def pick(result_ref, pkt):
    entropy = _entropy_from_ref(result_ref)
    rng = random.Random(int.from_bytes(hashlib.sha256(entropy + canonical(pkt)).digest(), "big"))
    weights = pkt["panel_weights"]
    u = rng.random() * sum(weights)
    for index, w in enumerate(weights):
        if u < w:
            return index
        u -= w
    return len(weights) - 1


def load_results():
    return json.loads(RESULTS.read_text(encoding="utf-8")) if RESULTS.exists() else {}


def render():
    m, results = method(), load_results()
    lines = ["# 2013 league awards: weekly and monthly", "",
             "Generated by `scripts/league_awards.py render` from `results.json`. Method: [methodology.json](methodology.json); see [README.md](README.md).", ""]
    for kind, title in (("month", "Monthly awards"), ("week", "Weekly awards")):
        periods = [k for k, v in results.items() if v["kind"] == kind]
        if not periods:
            continue
        lines += ["## " + title, ""]
        for period in sorted(periods, key=lambda p: results[p]["order"]):
            entry = results[period]
            lines += ["### " + entry["label"], "",
                      "| Award | Winner | Team | Score | Shortlist (score) |", "|---|---|---|--:|---|"]
            for award in entry["awards"]:
                a = entry["awards"][award]
                w = a["shortlist"][a["winner_index"]]
                short = "; ".join("%s, %s (%.1f)" % (s["player"], s["team"], s["score"]) for s in a["shortlist"])
                lines.append("| %s | %s | %s | %.1f | %s |" % (m["award_names"][award], w["player"], w["team"], w["score"], short))
            lines += ["", entry.get("note", ""), ""]
    (AWARDS / "weekly_and_monthly.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("kind", choices=("week", "month", "render"))
    parser.add_argument("key", nargs="?")
    parser.add_argument("--close", action="store_true")
    parser.add_argument("--note", default="")
    parser.add_argument("--season", type=int, default=2013,
                        help="season (only 2013's award method and results exist)")
    args = parser.parse_args()
    if args.season != 2013:
        # The method, results and receipts here are 2013's. A later season
        # needs its own career/<season>/awards method first; never 2013's.
        print("AWARDS: BLOCKED - no %d award method; this script reads and writes "
              "career/2013/awards only" % args.season)
        return 1
    if args.kind == "render":
        render()
        return 0
    m = method()
    lists = shortlists(args.kind, args.key, m)
    for award, rows in lists.items():
        print(award, "; ".join("%s (%s) %.2f" % (r["player"], r["team"], r["score"]) for r in rows))
    if not args.close:
        return 0
    results = load_results()
    period = "%s-%s" % (args.kind, args.key)
    if period in results:
        print("AWARDS: %s already drawn" % period)
        return 1
    from runtime.private_client import Client
    client = Client()
    snapshot = client.current_snapshot()
    entry = {"kind": args.kind, "key": str(args.key),
             "label": ("Week %d" % int(args.key)) if args.kind == "week" else m["months"][args.key]["label"],
             "order": (int(args.key) if args.kind == "week" else 100 + m["months"][args.key]["order"]),
             "note": args.note, "awards": {}}
    for award, rows in lists.items():
        pkt = packet(args.kind, args.key, award, rows, m, snapshot)
        ref = client.close_event(pkt)
        entry["awards"][award] = {"event_id": pkt["event_id"], "packet_sha256": hashlib.sha256(canonical(pkt)).hexdigest(),
                                  "result_ref": ref, "shortlist": rows, "winner_index": pick(ref, pkt)}
    results[period] = entry
    RESULTS.write_text(json.dumps(results, indent=1) + "\n", encoding="utf-8")
    render()
    return 0


if __name__ == "__main__":
    sys.exit(main())
