#!/usr/bin/env python3
"""Refresh DOB/age columns and the league view from Document 5's master date.

Run after closing a date or changing roster control. --check is read-only.
It never advances the clock, retires a player or changes a game packet.
"""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from runtime.player_bios import biographies, load, master_date
from runtime.seasons import current_record
from runtime.season_layout import rebase_markdown

STAMP = re.compile(r"^<!-- player-ages-as-of: [^\n]+ -->$", re.M)


def table_ages(text, day, players):
    """Update only tables with Player, position and a control status column."""
    output, header = [], None
    for line in text.splitlines():
        if not line.startswith("|"):
            header = None
            output.append(line)
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if "Player" in cells:
            header = cells if any(c in cells for c in ("Pos", "Pos.")) and any(
                c in cells for c in ("Status", "Primary status")) else None
        if header is None:
            output.append(line)
            continue
        # Rebuild columns so re-running is idempotent and parser positions hold.
        keep = [i for i, c in enumerate(header) if c not in {"DOB", "Age"}]
        clean = [cells[i] for i in keep]
        clean_header = [header[i] for i in keep]
        pos = next(i for i, c in enumerate(clean_header) if c in {"Pos", "Pos."}) + 1
        if "Player" in cells:
            extra = ["DOB", "Age"]
        elif set(cells[0]) <= {"-", ":"}:
            extra = ["---", "---:"]
        else:
            bio = biographies([cells[header.index("Player")]], day, players)
            row = next(iter(bio.values()))
            extra = [row["birth_date"], str(row["age"])]
        output.append("| " + " | ".join(clean[:pos] + extra + clean[pos:]) + " |")
    return STAMP.sub("<!-- player-ages-as-of: %s -->" % day, "\n".join(output) + "\n")


def controlled_rows(text):
    header = None
    for line in text.splitlines():
        if not line.startswith("|"):
            header = None
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if "Player" in cells:
            header = cells if "Pos" in cells and "Status" in cells else None
        elif header and not set(cells[0]) <= {"-", ":"}:
            yield cells[header.index("Player")], cells[header.index("Pos")], cells[header.index("Status")]


def render_views(root=ROOT):
    root = Path(root)
    day, players = master_date(root), load(root)
    result = {}
    roster_path = current_record('roster', root).relative_to(root.resolve()).as_posix()
    for path in (roster_path, "state/04_Roster_and_Staff_Register.md"):
        text = (root / path).read_text(encoding="utf-8")
        if len(STAMP.findall(text)) != 1:
            raise ValueError("Expected one age as-of marker in " + path)
        result[path] = table_ages(text, day, players)
    clubs = json.loads(current_record('background_depth', root).read_text())["clubs"]
    controlled = list(controlled_rows(result[roster_path]))
    names = {n for n, _, _ in controlled}
    sections = {team: [(p["player_id"], p["position"], "Background roster")
                       for p in c["players"] if p["player_id"] not in names]
                for team, c in clubs.items()}
    sections["Jacksonville Jaguars"] = controlled
    lines = ["# Player ages", "", "**As of:** %s (Document 5 master date)." % day, "",
             "Generated by `python scripts/render_player_ages.py`. Ages count completed birthdays.",
             "Birth dates and evidence: [registry](../../library/data/player_birth_dates.json) and "
             "[verification notes](../../library/2013_player_birth_dates.md).", "",
             "Jacksonville includes every controlled player, including the practice squad. Other clubs "
             "use the branch background roster library; these rows do not confer game-day eligibility.", ""]
    for team, rows in sorted(sections.items()):
        lines += ["## " + team, "", "| Player | Pos | DOB | Age | Roster scope |",
                  "|---|---|---|---:|---|"]
        bios = biographies([n for n, _, _ in rows], day, players)
        for name, pos, status in rows:
            bio = bios[name]
            lines.append("| %s | %s | %s | %s | %s |" % (name, pos, bio["birth_date"], bio["age"], status))
        lines.append("")
    target = current_record('player_ages', root).relative_to(root.resolve()).as_posix()
    year = target.split('/')[1]
    result[target] = rebase_markdown('\n'.join(lines), f'career/{year}/player_ages.md', target)
    return result


def check(root=ROOT):
    return ["Player ages stale: %s; run python scripts/render_player_ages.py" % path
            for path, expected in render_views(root).items()
            if not (Path(root) / path).exists() or (Path(root) / path).read_text(encoding="utf-8") != expected]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        errors = check()
        print("\n".join(errors) if errors else "PASS: player ages match the simulation date")
        return bool(errors)
    for path, text in render_views().items():
        (ROOT / path).write_text(text, encoding="utf-8")
    print("Updated roster, register and league player ages from Document 5")
    return 0


if __name__ == "__main__":
    sys.exit(main())
