"""Renders library/2010_2014_player_state_study.md from the player-state model (kernel 2014.6, batch B4b).

Every number in the study comes from library/data/2010_2014_player_state_model.json or the
public table; nothing is typed. Called by build_2010_2014_player_state_model.py, whose --check
compares the rendered text with the committed file.
"""
from __future__ import annotations


def _f(x, d=4):
    if x is None:
        return "-"
    return ("%%.%dg" % d) % x


def _cap(text):
    return text[:1].upper() + text[1:]


def render(model, public, _previous=None):
    fams = model["families"]
    L = []
    w = L.append
    w("# 2010-2014 player-state study (kernel 2014.6, batch B4b)")
    w("")
    w("[Engine decisions](../runtime/2014_engine_decisions.md#kernel-20146-decisions-dated) · "
      "[Pre-build specification](2014_6_pre_build_specification.md) · [Strength studies](2014_strength_calibration.md)")
    w("")
    w("**What this is.** The data-only record of the player-state model Stone adopted on October 2, 2026 (policy A to D): "
      "a hidden-state statistical prior per player for the engine, built from public 2010-2014 data. Generated by "
      "`scripts/research/build_2010_2014_player_state_model.py` (pass 1) with "
      "`scripts/research/verify_2010_2014_player_state_model.py` (pass 2); both have `--check`. Machine records: "
      "[`data/2010_2014_player_state_model.json`](data/2010_2014_player_state_model.json), "
      "[`data/2014_player_state_public.json`](data/2014_player_state_public.json) and "
      "[`data/2014_player_state_manifest.json`](data/2014_player_state_manifest.json). Nothing in the runtime reads "
      "them until batch B7, and no game has used them.")
    w("")
    w("**Boundary.** %s. A real player's own 2013-2014 statistics never set his own value: the public table is built "
      "from each player's 2010-2012 lines only, and 2013 and 2014 Weeks 1-4 enter the pooled fits as an anonymous "
      "league population. The public table holds expectations only; the once-per-season draw is made and recorded "
      "by the private service from batch B7, and no one sees it." % _cap(model["boundary"]))
    w("")
    u5 = model["u5"]
    w("**U5 is unanswered, so this build uses the fallback.** %s. Held, never replaced: %s." % (
        _cap(u5["effect"]), ", ".join(u5["held"])))
    w("")
    w("## 1. Families, metrics and floors")
    w("")
    w("| Family | Metric | Floor | Players in the swing fit |")
    w("|---|---|---:|---:|")
    for k, b in fams.items():
        w("| %s | %s | %s | %d |" % (k, b["metric"], b["floor"], b["pass1"]["players"]))
    w("")
    w("Offensive linemen and long snappers have no public performance rate and no state (the runtime keeps rule B "
      "plus honours for linemen).")
    w("")
    w("## 2. The swing: size and carry")
    w("")
    w("Lag-k covariance C_k = sb2 + rho^k su2 over lags 0-4 (the 2013-to-2014 Weeks 1-4 pair held out), fitted on a "
      "0.01 grid of rho. Kept only if su2's bootstrap 95%% interval (%d resamples of players) excludes 0 in both passes; "
      "size from pass 1 when pass 2's point lies inside pass 1's interval, otherwise the smaller." %
      fams["QB"]["pass1"]["bootstrap"]["resamples"])
    w("")
    w("| Family | Pass 1 sb2 | Pass 1 su2 | Pass 1 rho | Pass 1 su2 interval | Pass 2 su2 | Pass 2 rho | Pass 2 su2 "
      "interval | Status | Adopted sb2 | su2 | rho | tau |")
    w("|---|---:|---:|---:|---|---:|---:|---|---|---:|---:|---:|---:|")
    second = model["second_pass"]["families"]
    for k, b in fams.items():
        p1, p2, a = b["pass1"], second[k]["fit"], b["adopted"]
        status = a["status"] + ("; **held (U5)**" if a.get("held") else "")
        w("| %s | %s | %s | %s | %s to %s | %s | %s | %s to %s | %s | %s | %s | %s | %s |" % (
            k, _f(p1["sb2"]), _f(p1["su2"]), _f(p1["rho"], 2), _f(p1["bootstrap"]["su2_interval"][0]),
            _f(p1["bootstrap"]["su2_interval"][1]), _f(p2["su2"]), _f(p2["rho"], 2),
            _f(p2["bootstrap"]["su2_interval"][0]), _f(p2["bootstrap"]["su2_interval"][1]), status,
            "-" if a.get("held") else _f(a["sb2"]), "-" if a.get("held") else _f(a["su2"]),
            "-" if a.get("held") else _f(a["rho"], 2), "-" if a.get("held") else _f(a["tau"])))
    w("")
    for k, b in fams.items():
        if b["adopted"].get("held"):
            w("- **%s held.** %s" % (k, b["adopted"]["held_reason"]))
    w("")
    w("A family whose swing is not kept carries no once-per-season draw; its persistent spread is the same least-squares "
      "fit with su2 fixed at 0 (every lag moment pooled). Fitted against empirical lag moments (the AR(1) fit's "
      "misfit, pass 1):")
    w("")
    w("| Family | lag 0 | lag 1 | lag 2 | lag 3 | lag 4 |")
    w("|---|---|---|---|---|---|")
    for k, b in fams.items():
        w("| %s | %s |" % (k, " | ".join("%s / %s (%d)" % (_f(m["moment"]), _f(m["fitted"]), m["terms"])
                                       for m in b["pass1"]["lag_moments"])))
    w("")
    w("## 3. Draft-slot starting estimates (flat under the U5 fallback)")
    w("")
    w("First and second seasons above the floor; each player's own class left out when his prior is formed; the real "
      "selection slot or undrafted status for every club, Jacksonville's included (U4). The log-pick slope is fitted "
      "and reported, and applied at 0.")
    w("")
    w("| Family | Drafted mean (SE, lines) | Undrafted mean (SE, lines) | Fitted log-pick slope (SE) | Applied |")
    w("|---|---|---|---|---|")
    for k, b in fams.items():
        d = b["draft_priors"]

        def cell(s):
            return "-" if not s else "%s (%s, %d)" % (_f(s["mean"]), _f(s["se"], 2), s["lines"])
        sl = d["log_pick_slope"]
        w("| %s | %s | %s | %s | %s |" % (k, cell(d["drafted"]["all"]), cell(d["undrafted"]["all"]),
                                         "-" if sl["slope"] is None else "%s (%s)" % (_f(sl["slope"]), _f(sl["se"], 2)),
                                         _f(sl["applied"])))
    w("")
    w("Cells under the amendment-3 minimum of 30 are flagged, not merged (the rule is held): %s." % "; ".join(
        "%s: %s" % (k, ", ".join(b["below_min_cell"])) for k, b in fams.items() if b["below_min_cell"]))
    w("")
    w("## 4. Honours as a pseudo-observation")
    w("")
    w("An admissible honour (AP All-Pro first or second team, or an original Pro Bowl, public before the cutoff) is "
      "one more observation of that season's state, split between the persistent and swing parts by the Kalman gain: "
      "its value is the family's mean among honoured qualifier seasons and its variance their true-state dispersion "
      "over the evidence weight (1.0 Confirmed two-pass, 0.5 Single-pass).")
    w("")
    w("| Family | Honoured seasons | Mean | True-state variance |")
    w("|---|---:|---:|---:|")
    for k, b in fams.items():
        c = b["honour_cell"]
        w("| %s | %s | %s | %s |" % (k, c["seasons"] if c else "-", _f(c["mean"]) if c else "no estimable cell",
                                     _f(c["true_var"]) if c else "-"))
    w("")
    w("## 5. Checks")
    w("")
    w("**Forecast calibration on the held-out pair** (each qualifying 2014 Weeks 1-4 line forecast from the player's "
      "lines through 2013; z = error over the forecast's own SD; within 2 SE means |mean z| and |var z - 1| inside "
      "two standard errors):")
    w("")
    w("| Family | Players | Mean z (SE) | Var z (SE) | Status |")
    w("|---|---:|---|---|---|")
    for k, b in fams.items():
        c = b["forecast_calibration_2013_to_2014w4"]
        if "mean_z" in c:
            w("| %s | %d | %s (%s) | %s (%s) | %s |" % (k, c["players"], _f(c["mean_z"], 3), _f(c["se_mean"], 2),
                                                      _f(c["var_z"], 3), _f(c["se_var"], 2), c["status"]))
        else:
            w("| %s | %s | - | - | %s |" % (k, c.get("players", "-"), c["status"]))
    w("")
    w("**Two-pass agreement** (each tolerance 2 SE from pass 1's own n; quantities outside are flagged and the pass-1 "
      "value is used): %s." % "; ".join(
          "%s %d of %d outside" % (k, b["two_pass_agreement"]["outside"], len(b["two_pass_agreement"]["rows"]))
          for k, b in fams.items()))
    w("")
    w("**Drift (R13).** Per-season centres and lag-1 covariances by season pair with bootstrap SEs and Cochran's Q "
      "(reported; the pooled fit is used whatever it reads):")
    w("")
    w("| Family | Centres 2010 / 2011 / 2012 / 2013 / 2014w4 | Level Q (df), p | Lag-1 covariance by pair | Q (df), p |")
    w("|---|---|---|---|---|")
    for k, b in fams.items():
        dr = b["drift"]
        h = dr["heterogeneity"]
        lh = dr["level_heterogeneity"]
        w("| %s | %s | %s | %s | %s |" % (
            k, " / ".join(_f(v["centre"]) for _, v in sorted(dr["levels"].items())),
            "-" if lh["cochran_q"] is None else "%s (%d), %s" % (_f(lh["cochran_q"], 3), lh["df"], _f(lh["p"], 2)),
            "; ".join("%s %s (%s)" % (p, _f(v["covariance"]), _f(v["se"], 2)) for p, v in sorted(dr["lag1_pairs"].items())),
            "-" if h["cochran_q"] is None else "%s (%d), %s" % (_f(h["cochran_q"], 3), h["df"], _f(h["p"], 2))))
    w("")
    w("**Self-influence** (a player's own 2013-2014 rows removed from the moment sums, his 2014 expectation "
      "recomputed; in the family's true-state SD; summaries over every such player, none stored per player):")
    w("")
    w("| Family | Players | Median | 90th | 99th | Max |")
    w("|---|---:|---:|---:|---:|---:|")
    for k, b in fams.items():
        s = b["self_influence"]
        if s.get("players"):
            w("| %s | %d | %s | %s | %s | %s |" % (k, s["players"], _f(s["median"], 2), _f(s["p90"], 2),
                                                   _f(s["p99"], 2), _f(s["max"], 2)))
        else:
            w("| %s | - | - | - | - | %s |" % (k, s.get("status") or s.get("note") or "-"))
    w("")
    w("**Tiers:** %s (%s)." % (model["tiers"]["status"], model["tiers"]["why"]))
    w("")
    w("## 6. Feedback (D): fitted, applied at 0 in 2014")
    w("")
    fb = model["feedback"]
    w("Outcome: %s. Snaps carry weight %s (no public 2010-2012 snap counts). Role is applied at %s for the 2015 "
      "transition until Stone decides (default 1B.13); availability %s." % (
          fb["outcome"], fb["applied"]["snaps"], fb["applied"]["role_2015"], fb["applied"]["availability"]))
    w("")
    w("| Term | Pass 1 slope (SE) | Pass 1 LOO-club skill | Cap quantile | Pass 2 slope (SE) | Pass 2 skill | Kept | "
      "Weight |")
    w("|---|---|---:|---:|---|---:|---|---:|")
    for term in ("role", "availability"):
        a, b, r = fb["pass1"][term], fb["pass2"][term], fb["reconciled"][term]
        w("| %s | %s (%s) | %s | %s | %s (%s) | %s | %s | %s |" % (
            term, _f(a["slope"]), _f(a["se"], 2), _f(a["loo_club_skill"], 3), _f(a["cap_quantile"], 2),
            _f(b["slope"]), _f(b["se"], 2), _f(b["loo_club_skill"], 3),
            ("yes, " + r["status"]) if r["kept"] else "no", _f(r["weight"])))
    w("")
    w("In real data a role change partly reflects coaches' information about talent, not development caused by playing "
      "time; applying it causally would be Stone's policy, not something this fit establishes.")
    w("")
    w("## 7. The 2014 public table")
    w("")
    cov = public["coverage"]
    w("Rows for every player in the [branch identity table](../career/2014/League/personnel/branch_identity.json), "
      "keyed by gsis id, with no club field: record family, basis, m_b, m_u, P = [Pbb, Pbu, Puu], the honours lift, "
      "the age on September 1, 2014 (recorded, unused under Z aging), class and real selection slot, and the 2010-2012 source rows. Bases: %s." %
      ", ".join("%s %d" % kv for kv in sorted(cov.items())))
    w("")
    w("- record: carried from his own 2010-2012 lines; draft or undrafted: the flat starting estimate for his class "
      "(his own class left out); population: a veteran entering before 2010 with no line, N(0, diag(sb2, su2)); "
      "held: a family held under U5; no_state: offensive linemen, long snappers and players with no family.")
    w("- The table is append-only for later entrants; once batch B7 binds the season, an edit to an existing row is "
      "refused.")
    w("")
    w("## 8. Honest limits")
    w("")
    w("- Five seasons, one of them four weeks long, identify the persistent-versus-swing split weakly; the bootstrap "
      "intervals say so family by family.")
    w("- Survivorship and selection on opportunity remain: players who leave are unobserved, and a rookie prior "
      "describes a rookie who reaches the floor.")
    w("- An honour pulls a player toward the honoured group's mean, so for a player already estimated above that mean "
      "the honours lift is negative; the runtime's honour floor (batch B7) is a separate rule.")
    w("- Undrafted rookie cells are small in several families (section 3); with the minimum-cell rule held, their "
      "means stand as computed, with their standard errors.")
    w("- The disruption metric counts games with a recorded statistic, not snaps; the noise moment and the floors are "
      "per game.")
    w("- These are priors on a hidden engine value. They are not scouting evidence, not a grade and not a forecast "
      "of any real player's 2014 season.")
    return "\n".join(L) + "\n"
